using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum MissionType
{
    complete50Waves = 0,
    complete100Waves = 22,
    complete200Waves = 23,
    complete300Waves = 24,
    eliminate100Enemies = 1,
    eliminate500Enemies = 18,
    eliminate1000Enemies = 19,
    eliminate2000Enemies = 20,
    currencyCollected = 3,
    currencyCollected2 = 17,
    premiumCurrencyCollected = 2,
    premiumCurrencyCollected2 = 16,
    totalDamageReceived = 4,
    totalDamageReceived1 = 5,
    totalDamageReceived2 = 6,
    weaponSpecialist = 8,
    fusionFanatic = 9,
    burnThemDown = 10,
    shockwaveSpecialist = 11,
    explorationExpert = 13,
    explorationExpert2 = 40,
    explorationExpert3 = 41,
    criticalHitMastery = 14,
    bossHunter = 21,
    bossHunter2 = 39,
    multiKills = 31,
    multiKills2 = 36,
    multiKills3 = 37,
    multiKills4 = 38,
    cardsUsed = 32,
    upgradesPurchased = 33,
    upgradesPurchased2 = 34,
    upgradesPurchased3 = 35,
    stunEnemies = 42,
    slowEnemies = 43,
    weakenEnemies = 44,
    confuseEnemies = 45,
    paralyzeEnemies = 46,
    fearEnemies = 47,
    evolveEnemies = 48,
    evolveEnemies2 = 49,
    evolveEnemies3 = 50,
    evolveEnemies4 = 51,
    evolveEnemies5 = 52,
    
}